# Generated by Django 4.2.14 on 2024-08-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobsmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobappliersmodel',
            name='msg',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='jobappliersmodel',
            name='state',
            field=models.CharField(choices=[('1', 'تم التقديم'), ('2', 'مقبول'), ('3', 'مرفوض')], default='0', max_length=255, null=True, verbose_name='المؤهل المطلوب'),
        ),
        migrations.AlterField(
            model_name='jobsmodel',
            name='number_of_days_closing_job',
            field=models.IntegerField(default=30, verbose_name='عدد الايام للاغلاق الوظيفة تلقائيا'),
        ),
        migrations.AlterField(
            model_name='jobsmodel',
            name='state',
            field=models.CharField(choices=[('0', 'قيد المراجعة'), ('1', 'مفتوح'), ('2', 'مغلق'), ('3', 'اخفاء')], default='0', max_length=255, null=True, verbose_name='المؤهل المطلوب'),
        ),
    ]
