# Generated by Django 4.2.14 on 2024-08-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobappliersmodel_msg_alter_jobappliersmodel_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobappliersmodel',
            name='state',
            field=models.CharField(choices=[('1', 'تم التقديم'), ('2', 'مقبول'), ('3', 'مرفوض')], default='1', max_length=255, null=True, verbose_name='المؤهل المطلوب'),
        ),
    ]
