# Generated by Django 4.2.14 on 2024-09-03 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_jobappliersmodel_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsmodel',
            name='job_type',
            field=models.CharField(choices=[('1', 'دوام كامل'), ('2', 'دوام جزئي'), ('3', 'عن بعد'), ('4', 'متدرب'), ('5', 'متطوع')], max_length=255, null=True, verbose_name='الجنس'),
        ),
    ]
