# Generated by Django 4.2.14 on 2024-09-07 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_jobsmodel_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsmodel',
            name='cert_type',
            field=models.CharField(choices=[('6', 'المرحلة الابتدائية'), ('1', 'المرحلة الثانوية'), ('2', 'دبلوم'), ('3', 'البكالوريوس'), ('4', 'ماجستير'), ('5', 'دكتوراة')], max_length=255, null=True, verbose_name='المؤهل المطلوب'),
        ),
    ]
