# Generated by Django 4.2.14 on 2024-09-17 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_jobsmodel_cert_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsmodel',
            name='has_complited',
            field=models.BooleanField(default=False, verbose_name='تم مراجعتها من قبل'),
        ),
    ]
