# Generated by Django 4.2.14 on 2024-09-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_jobsmodel_has_complited'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSalariesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='اسم الراتب')),
            ],
        ),
    ]
