# Generated by Django 4.2.14 on 2024-09-18 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_jobsalariesmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsmodel',
            name='monthly_salary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.jobsalariesmodel', verbose_name='الراتب الشهري'),
        ),
    ]
