# Generated by Django 4.2.14 on 2024-09-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_alter_jobsmodel_monthly_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsmodel',
            name='state',
            field=models.CharField(choices=[('0', 'قيد المراجعة'), ('1', 'مفتوح'), ('2', 'مغلق'), ('3', 'رفض')], default='0', max_length=255, null=True, verbose_name='المؤهل المطلوب'),
        ),
    ]
