# Generated by Django 4.2.14 on 2024-11-02 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0087_alter_sendnotifications_status'),
        ('jobs', '0011_alter_jobsmodel_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsmodel',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.countrysmodel', verbose_name='الدولة المستهدفة'),
        ),
    ]
