# Generated by Django 4.2.14 on 2024-12-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_jobsmodel_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsmodel',
            name='job_type',
            field=models.CharField(choices=[('1', 'دوام كامل'), ('2', 'دوام جزئي'), ('3', 'عن بعد'), ('4', 'متدرب'), ('5', 'تدريب مهني بالتوظيف')], max_length=255, null=True, verbose_name='الجنس'),
        ),
    ]
