# Generated by Django 4.2.14 on 2024-09-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettingsmodel',
            name='email',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='generalsettingsmodel',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='phone'),
        ),
    ]
