# Generated by Django 4.2.14 on 2024-11-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_generalsettingsmodel_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettingsmodel',
            name='allow_company_signup',
            field=models.BooleanField(default=True, verbose_name='السماح للشركات التسجيل'),
        ),
    ]
