# Generated by Django 4.2.14 on 2024-12-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_generalsettingsmodel_allow_company_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettingsmodel',
            name='allow_employee_signup',
            field=models.BooleanField(default=True, verbose_name='السماح للموظفين التسجيل'),
        ),
    ]
