# Generated by Django 4.2.14 on 2024-08-08 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_alt_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='height',
            field=models.IntegerField(null=True, verbose_name='الطول'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='weight',
            field=models.IntegerField(null=True, verbose_name='الوزن'),
        ),
    ]
