# Generated by Django 4.2.14 on 2024-08-08 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_employeeprofile_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='about_me',
            field=models.TextField(null=True, verbose_name='نبذة عني'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='desires',
            field=models.JSONField(null=True, verbose_name='الرغبات json'),
        ),
    ]
