# Generated by Django 4.2.14 on 2024-08-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_employeeprofile_about_me_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='employee_city',
            field=models.CharField(max_length=255, null=True, verbose_name='المدينة'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='health_status',
            field=models.CharField(choices=[('0', 'صحي'), ('1', 'معاق')], max_length=255, null=True, verbose_name='الحالة الصحية'),
        ),
    ]
