# Generated by Django 4.2.14 on 2024-08-11 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_companyprofile_employee_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='facebook',
            field=models.CharField(max_length=250, null=True, verbose_name='facebook'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='linkedin',
            field=models.CharField(max_length=250, null=True, verbose_name='linkedin'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='whatsapp',
            field=models.CharField(max_length=250, null=True, verbose_name='whatsapp'),
        ),
    ]
