# Generated by Django 4.2.14 on 2024-08-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_employeeprofileimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofileimages',
            name='img_base64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeprofileimages',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='users/profile/imgs/%Y/%m/%d'),
        ),
    ]
