# Generated by Django 4.2.14 on 2024-08-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_employeeprofileimages_img_base64_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='about_me',
            field=models.TextField(null=True, verbose_name='نبذة عني'),
        ),
    ]
