# Generated by Django 4.2.14 on 2024-08-11 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_companyprofile_about_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='img_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
