# Generated by Django 4.2.14 on 2024-08-11 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_companyprofile_img_base64'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company_signup_process',
            field=models.CharField(choices=[('0', 'ملغي'), ('1', 'إنشاء حساب'), ('2', 'تاكيد الحساب'), ('3', 'إعداد ملف شخصي'), ('4', 'قيد المراجعة'), ('5', 'مكتمل')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cv_signup_process',
            field=models.CharField(choices=[('0', 'ملغي'), ('1', 'إنشاء حساب'), ('2', 'تاكيد الحساب'), ('3', 'إعداد ملف شخصي'), ('4', 'بناء سيرتك الذاتية'), ('5', 'قيد المراجعة'), ('6', 'مكتمل')], max_length=255, null=True),
        ),
    ]
