# Generated by Django 4.2.14 on 2024-08-11 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_userprofile_company_signup_process_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='company_signup_process',
            field=models.CharField(choices=[('0', 'ملغي'), ('1', 'إنشاء حساب'), ('2', 'إعداد ملف شخصي'), ('3', 'تاكيد الحساب'), ('4', 'قيد المراجعة'), ('5', 'مكتمل')], default='1', max_length=255, null=True),
        ),
    ]
