# Generated by Django 4.2.14 on 2024-08-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_userprofile_company_signup_process'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='skils',
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='skils',
            field=models.TextField(null=True, verbose_name='المهارات'),
        ),
    ]
