# Generated by Django 4.2.14 on 2024-08-16 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_employeeprofile_skils_employeeprofile_skils'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='last_active_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
