# Generated by Django 4.2.14 on 2024-08-16 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_companyprofile_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='last_active_datetime',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_active_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
