# Generated by Django 4.2.14 on 2024-08-17 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0017_userprofile_active_messenger_userprofile_is_in_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField()),
                ('is_readed', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(null=True, verbose_name='تاريخ الانشاء')),
                ('receiver', models.ManyToManyField(related_name='noti_receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noti_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
