# Generated by Django 4.2.14 on 2024-08-17 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_userprofile_money_referrallinkmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='referral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.referrallinkmodel', verbose_name=''),
        ),
    ]
