# Generated by Django 4.2.14 on 2024-08-18 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_jobsmodel_referrallinkmodel_creation_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobAppliersModel',
        ),
        migrations.DeleteModel(
            name='JobsModel',
        ),
    ]
