# Generated by Django 4.2.14 on 2024-08-20 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_employeeprofile_desires'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('ico', models.TextField()),
                ('number_of_days', models.IntegerField(default=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('daily_number_of_receive_msgs', models.IntegerField(default=1)),
                ('daily_number_of_send_msgs', models.IntegerField(default=1)),
                ('number_of_view_profiles', models.IntegerField(default=1)),
                ('show_phone', models.BooleanField(default=False)),
                ('show_whats', models.BooleanField(default=False)),
                ('show_facebook', models.BooleanField(default=False)),
                ('show_linkedin', models.BooleanField(default=False)),
                ('show_instgram', models.BooleanField(default=False)),
                ('show_snap', models.BooleanField(default=False)),
                ('show_tiktok', models.BooleanField(default=False)),
                ('show_userprofile_img', models.BooleanField(default=False)),
                ('distinctive_mark', models.BooleanField(default=False)),
                ('distinctive', models.BooleanField(default=False)),
                ('show_number_of_appearances', models.BooleanField(default=False)),
                ('show_number_of_likes', models.BooleanField(default=False)),
                ('referral_link_to_earn', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(null=True, verbose_name='تاريخ الانشاء')),
            ],
        ),
    ]
