# Generated by Django 4.2.14 on 2024-08-20 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_subscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='Theem',
            field=models.CharField(choices=[('btn btn-primary', 'primary'), ('btn btn-secondary', 'secondary'), ('btn btn-success', 'success'), ('btn btn-danger', 'danger'), ('btn btn-warning', 'warning'), ('btn btn-info', 'info'), ('btn btn-light', 'light'), ('btn btn-dark', 'dark')], max_length=255, null=True),
        ),
    ]
