# Generated by Django 4.2.14 on 2024-08-21 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0029_rename_subscriptions_subscriptionsmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserViewedProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ignore_subscription', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(null=True, verbose_name='تاريخ الانشاء')),
                ('profile_viewed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_viewed', to=settings.AUTH_USER_MODEL)),
                ('profile_viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_viewer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
