# Generated by Django 4.2.14 on 2024-08-21 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_userviewedprofilemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionsmodel',
            old_name='daily_number_of_receive_msgs',
            new_name='number_of_receive_msgs',
        ),
        migrations.RenameField(
            model_name='subscriptionsmodel',
            old_name='daily_number_of_send_msgs',
            new_name='number_of_send_msgs',
        ),
        migrations.RenameField(
            model_name='usersubscriptionmodel',
            old_name='daily_number_of_receive_msgs',
            new_name='number_of_receive_msgs',
        ),
        migrations.RenameField(
            model_name='usersubscriptionmodel',
            old_name='daily_number_of_send_msgs',
            new_name='number_of_send_msgs',
        ),
    ]
