# Generated by Django 4.2.14 on 2024-08-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_usersubscriptionmodel_used_number_of_receive_msgs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscriptionmodel',
            name='used_number_of_receive_msgs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usersubscriptionmodel',
            name='used_number_of_send_msgs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usersubscriptionmodel',
            name='used_number_of_view_profiles',
            field=models.IntegerField(default=0),
        ),
    ]
