# Generated by Django 4.2.14 on 2024-08-21 08:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_alter_usersubscriptionmodel_used_number_of_receive_msgs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscriptionmodel',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='تاريخ الانشاء'),
        ),
    ]
