# Generated by Django 4.2.14 on 2024-08-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_alter_userprofile_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionsmodel',
            name='is_default_Subscription',
            field=models.BooleanField(default=False, verbose_name='هل هذه الباقة الافتراضية عند التسجيل'),
        ),
    ]
