# Generated by Django 4.2.14 on 2024-08-21 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_subscriptionsmodel_is_default_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='referrallinkmodel',
            name='alias_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
