# Generated by Django 4.2.14 on 2024-08-22 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0040_userprofile_dont_receive_msg_from_companys_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPaymentOrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, null=True, verbose_name='الاسم الثلاثي')),
                ('price', models.CharField(max_length=250, null=True, verbose_name='الاسم الثلاثي')),
                ('clientName', models.CharField(max_length=250, null=True, verbose_name='الاسم الثلاثي')),
                ('card', models.JSONField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
