# Generated by Django 4.2.14 on 2024-08-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_userpaymentordermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpaymentordermodel',
            name='creation_date',
            field=models.DateTimeField(null=True, verbose_name='تاريخ الانشاء'),
        ),
        migrations.AddField(
            model_name='userpaymentordermodel',
            name='orderID',
            field=models.CharField(max_length=250, null=True, verbose_name='الاسم الثلاثي'),
        ),
    ]
