# Generated by Django 4.2.14 on 2024-08-24 10:10

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_userpaymentordermodel_creation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpaymentordermodel',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.subscriptionsmodel'),
        ),
        migrations.AlterField(
            model_name='userpaymentordermodel',
            name='orderID',
            field=models.CharField(default=accounts.models.payOrderCodeGen, max_length=250, null=True, verbose_name='الاسم الثلاثي'),
        ),
    ]
