# Generated by Django 4.2.14 on 2024-08-24 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_userpaymentordermodel_subscription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpaymentordermodel',
            name='card',
        ),
        migrations.RemoveField(
            model_name='userpaymentordermodel',
            name='clientName',
        ),
        migrations.RemoveField(
            model_name='userpaymentordermodel',
            name='price',
        ),
        migrations.RemoveField(
            model_name='userpaymentordermodel',
            name='title',
        ),
    ]
