# Generated by Django 4.2.14 on 2024-08-24 12:45

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0046_userpaymentordermodel_transactionno'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsappOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(default=accounts.models.WhatsappOTPCodeGen, max_length=250, null=True)),
                ('is_finshed', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(null=True, verbose_name='تاريخ الانشاء')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
