# Generated by Django 4.2.14 on 2024-08-29 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_subscriptionsmodel_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ip_info',
            field=models.JSONField(default=dict),
        ),
    ]
