# Generated by Django 4.2.14 on 2024-08-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_adminadsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminadsmodel',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
