# Generated by Django 4.2.14 on 2024-08-31 19:53

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_forgetpwdmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminadsmodel',
            name='is_main_ad',
            field=models.BooleanField(default=False, verbose_name='انه اعلان الرئيسي'),
        ),
        migrations.AddField(
            model_name='adminadsmodel',
            name='show_in_cv',
            field=models.BooleanField(default=False, verbose_name='اظهار بين السير'),
        ),
        migrations.AddField(
            model_name='adminadsmodel',
            name='show_on_all_countrys',
            field=models.BooleanField(default=False, verbose_name='عرض في جميع الدول'),
        ),
        migrations.AlterField(
            model_name='forgetpwdmodel',
            name='secret',
            field=models.CharField(default=accounts.models.ResetPWDCodeGen, max_length=250, null=True),
        ),
    ]
