# Generated by Django 4.2.14 on 2024-08-31 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_adminadsmodel_is_main_ad_adminadsmodel_show_in_cv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminadsmodel',
            name='show_in_others',
            field=models.BooleanField(default=False, verbose_name='اظهار بين الاقسام الاخرى للموقع'),
        ),
    ]
