# Generated by Django 4.2.14 on 2024-09-01 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0059_alter_adminadsmodel_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NationalityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='الجنسية')),
                ('creation_date', models.DateTimeField(null=True, verbose_name='تاريخ الانشاء')),
            ],
        ),
        migrations.AlterField(
            model_name='adminadsmodel',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.countrysmodel', verbose_name='الدولة'),
        ),
        migrations.AlterField(
            model_name='subscriptionpricebycountry',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.countrysmodel', verbose_name='الدولة'),
        ),
    ]
