# Generated by Django 4.2.14 on 2024-09-01 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_nationalitymodel_alter_adminadsmodel_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='nationality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.nationalitymodel', verbose_name='الجنسية'),
        ),
    ]
