# Generated by Django 4.2.14 on 2024-09-02 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0061_alter_employeeprofile_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminpermissionmodel',
            name='add_countrys',
            field=models.BooleanField(default=False, verbose_name='إضافة البلدان'),
        ),
        migrations.AddField(
            model_name='adminpermissionmodel',
            name='add_nationality',
            field=models.BooleanField(default=False, verbose_name='إضافة_جنسية'),
        ),
        migrations.AddField(
            model_name='adminpermissionmodel',
            name='delete_countrys',
            field=models.BooleanField(default=False, verbose_name='حذف_البلدان'),
        ),
        migrations.AddField(
            model_name='adminpermissionmodel',
            name='delete_nationality',
            field=models.BooleanField(default=False, verbose_name='حذف_الجنسية'),
        ),
        migrations.AddField(
            model_name='adminpermissionmodel',
            name='edit_countrys',
            field=models.BooleanField(default=False, verbose_name='تعديل_البلدان'),
        ),
        migrations.AddField(
            model_name='adminpermissionmodel',
            name='edit_nationality',
            field=models.BooleanField(default=False, verbose_name='تعديل_الجنسية'),
        ),
        migrations.AddField(
            model_name='adminpermissionmodel',
            name='show_countrys',
            field=models.BooleanField(default=False, verbose_name='إظهار البلدان'),
        ),
        migrations.AddField(
            model_name='adminpermissionmodel',
            name='show_nationality',
            field=models.BooleanField(default=False, verbose_name='إظهار_الجنسية'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='add_ads',
            field=models.BooleanField(default=False, verbose_name='إضافة إعلانات'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='add_custum_subscription',
            field=models.BooleanField(default=False, verbose_name='إضافة اشتراك مخصص'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='add_subscription',
            field=models.BooleanField(default=False, verbose_name='إضافة_اشتراك'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='delete_ads',
            field=models.BooleanField(default=False, verbose_name='حذف_الإعلانات'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='delete_companys',
            field=models.BooleanField(default=False, verbose_name='حذف_الشركات'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='delete_custum_subscription',
            field=models.BooleanField(default=False, verbose_name='حذف_الاشتراك_المخصص'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='delete_employees',
            field=models.BooleanField(default=False, verbose_name='حذف الموظفين'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='delete_jobs',
            field=models.BooleanField(default=False, verbose_name='حذف الوظائف'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='delete_subscription',
            field=models.BooleanField(default=False, verbose_name='حذف_الاشتراك'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='edit_ads',
            field=models.BooleanField(default=False, verbose_name='تعديل_الإعلانات'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='edit_companys',
            field=models.BooleanField(default=False, verbose_name='تعديل_الشركات'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='edit_custum_subscription',
            field=models.BooleanField(default=False, verbose_name='تعديل_الاشتراك_المخصص'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='edit_employees',
            field=models.BooleanField(default=False, verbose_name='تعديل_الموظفين'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='edit_jobs',
            field=models.BooleanField(default=False, verbose_name='تعديل الوظائف'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='edit_settings',
            field=models.BooleanField(default=False, verbose_name='تعديل الإعدادات'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='edit_subscription',
            field=models.BooleanField(default=False, verbose_name='تعديل الاشتراك'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='edit_user_subscription',
            field=models.BooleanField(default=False, verbose_name='تعديل اشتراك المستخدم'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='send_notifications',
            field=models.BooleanField(default=False, verbose_name='إرسال الإشعارات'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='show_ads',
            field=models.BooleanField(default=False, verbose_name='عرض الإعلانات'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='show_companys',
            field=models.BooleanField(default=False, verbose_name='عرض الشركات'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='show_custum_subscription',
            field=models.BooleanField(default=False, verbose_name='عرض الاشتراك المخصص'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='show_employees',
            field=models.BooleanField(default=False, verbose_name='عرض الموظفين'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='show_jobs',
            field=models.BooleanField(default=False, verbose_name='عرض الوظائف'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='show_subscription',
            field=models.BooleanField(default=False, verbose_name='عرض الاشتراك'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='show_user_subscription',
            field=models.BooleanField(default=False, verbose_name='إظهار اشتراك المستخدم'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
    ]
