# Generated by Django 4.2.14 on 2024-09-02 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0062_adminpermissionmodel_add_countrys_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminpermissionmodel',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='هل المسؤل مفعل'),
        ),
    ]
