# Generated by Django 4.2.14 on 2024-09-03 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0063_adminpermissionmodel_is_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='classes',
            field=models.JSONField(default=dict, null=True, verbose_name='دورات json'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='experiences',
            field=models.JSONField(default=dict, null=True, verbose_name='خبرات json'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='lang',
            field=models.JSONField(default=dict, null=True, verbose_name='لغات json'),
        ),
        migrations.AlterField(
            model_name='adminpermissionmodel',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='هل المسؤول مفعل'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='skils',
            field=models.JSONField(default=dict, null=True, verbose_name='مهارات json'),
        ),
    ]
