# Generated by Django 4.2.14 on 2024-09-07 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0068_alter_employeeprofile_skils'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthStatusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='الحالة الصحية')),
                ('creation_date', models.DateTimeField(null=True, verbose_name='تاريخ الانشاء')),
            ],
        ),
        migrations.AlterField(
            model_name='subscriptionsmodel',
            name='Theem',
            field=models.CharField(choices=[('btn btn-primary', 'primary'), ('btn btn-secondary', 'secondary'), ('btn btn-success', 'success'), ('btn btn-danger', 'danger'), ('btn btn-warning', 'warning'), ('btn btn-info', 'info'), ('btn btn-light', 'light'), ('btn btn-dark', 'dark')], max_length=255, null=True, verbose_name='الثيم'),
        ),
        migrations.AlterField(
            model_name='subscriptionsmodel',
            name='currency',
            field=models.CharField(choices=[('SAR', 'ريال سعودي'), ('USD', 'دولار'), ('EUR', 'يورو')], default='USD', max_length=250, null=True, verbose_name='العملة'),
        ),
        migrations.AlterField(
            model_name='subscriptionsmodel',
            name='distinctive_frame',
            field=models.BooleanField(default=False, verbose_name='إطار مميز'),
        ),
        migrations.AlterField(
            model_name='subscriptionsmodel',
            name='distinctive_mark',
            field=models.BooleanField(default=False, verbose_name='علامة مميزة'),
        ),
        migrations.AlterField(
            model_name='subscriptionsmodel',
            name='ico',
            field=models.TextField(verbose_name='الأيقونة'),
        ),
        migrations.AlterField(
            model_name='subscriptionsmodel',
            name='number_of_days',
            field=models.IntegerField(default=30, verbose_name='عدد الأيام'),
        ),
        migrations.AlterField(
            model_name='subscriptionsmodel',
            name='number_of_receive_msgs',
            field=models.IntegerField(default=1, verbose_name='عدد الرسائل المستلمة'),
        ),
        migrations.AlterField(
            model_name='subscriptionsmodel',
            name='number_of_send_msgs',
            field=models.IntegerField(default=1, verbose_name='عدد الرسائل المرسلة'),
        ),
        migrations.AlterField(
            model_name='subscriptionsmodel',
            name='number_of_view_profiles',
            field=models.IntegerField(default=1, verbose_name='عدد مرات مشاهدة الملفات الشخصية'),
        ),
        migrations.AlterField(
            model_name='subscriptionsmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='السعر'),
        ),
        migrations.AlterField(
            model_name='subscriptionsmodel',
            name='referral_link_to_earn',
            field=models.BooleanField(default=False, verbose_name='رابط الإحالة للربح'),
        ),
        migrations.AlterField(
            model_name='subscriptionsmodel',
            name='show_facebook',
            field=models.BooleanField(default=False, verbose_name='إظهار الفيسبوك'),
        ),
        migrations.AlterField(
            model_name='subscriptionsmodel',
            name='show_instgram',
            field=models.BooleanField(default=False, verbose_name='إظهار الإنستغرام'),
        ),
        migrations.AlterField(
            model_name='subscriptionsmodel',
            name='show_linkedin',
            field=models.BooleanField(default=False, verbose_name='إظهار لينكدإن'),
        ),
        migrations.AlterField(
            model_name='subscriptionsmodel',
            name='show_number_of_appearances',
            field=models.BooleanField(default=False, verbose_name='إظهار عدد الظهور'),
        ),
        migrations.AlterField(
            model_name='subscriptionsmodel',
            name='show_number_of_likes',
            field=models.BooleanField(default=False, verbose_name='إظهار عدد الإعجابات'),
        ),
        migrations.AlterField(
            model_name='subscriptionsmodel',
            name='show_phone',
            field=models.BooleanField(default=False, verbose_name='إظهار رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='subscriptionsmodel',
            name='show_snap',
            field=models.BooleanField(default=False, verbose_name='إظهار السناب شات'),
        ),
        migrations.AlterField(
            model_name='subscriptionsmodel',
            name='show_tiktok',
            field=models.BooleanField(default=False, verbose_name='إظهار التيك توك'),
        ),
        migrations.AlterField(
            model_name='subscriptionsmodel',
            name='show_userprofile_img',
            field=models.BooleanField(default=False, verbose_name='إظهار صورة الملف الشخصي'),
        ),
        migrations.AlterField(
            model_name='subscriptionsmodel',
            name='show_whats',
            field=models.BooleanField(default=False, verbose_name='إظهار رقم الواتساب'),
        ),
        migrations.AlterField(
            model_name='subscriptionsmodel',
            name='subtitle',
            field=models.CharField(max_length=255, verbose_name='العنوان الفرعي'),
        ),
        migrations.AlterField(
            model_name='subscriptionsmodel',
            name='title',
            field=models.CharField(max_length=255, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='health_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.healthstatusmodel', verbose_name='الحالة الصحية'),
        ),
    ]
