# Generated by Django 4.2.14 on 2024-09-07 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0069_healthstatusmodel_alter_subscriptionsmodel_theem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='cert_type',
            field=models.CharField(choices=[('6', 'المرحلة الابتدائية'), ('1', 'المرحلة الثانوية'), ('2', 'دبلوم'), ('3', 'البكالوريوس'), ('4', 'ماجستير'), ('5', 'دكتوراة')], max_length=255, null=True, verbose_name='نوع الشهادة'),
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', 'Pending,, قيد الانتظار'), ('1', 'Approved,, وافق'), ('2', 'Complete,, مكتمل'), ('3', 'Cancelled,, ألغيت')], max_length=250, verbose_name='الحالة')),
                ('total_amount', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='كمية السحب')),
                ('withdrawal_method', models.CharField(choices=[('1', 'USDT')], max_length=250, verbose_name='نوع السحب')),
                ('usdt_network', models.CharField(blank=True, choices=[('0', 'Tron (TRC20)'), ('1', 'Ethereum (ERC20)'), ('2', 'BNB Smart Chain (BEP20)'), ('3', 'Solana'), ('4', 'Polygon'), ('5', 'Arbitrum One'), ('6', 'Optimism')], max_length=250, null=True, verbose_name='شبكة usdt')),
                ('usdt_address', models.CharField(blank=True, max_length=250, null=True, verbose_name='عنوان محفظة usdt')),
                ('desc', models.TextField(verbose_name='وصف')),
                ('is_completed', models.BooleanField(default=False, verbose_name='دفعت')),
                ('withdraw_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ السحب')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'ordering': ['-withdraw_date'],
            },
        ),
    ]
