# Generated by Django 4.2.14 on 2024-09-07 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0070_alter_employeeprofile_cert_type_withdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='IBAN_number',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='عنوان محفظة usdt'),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='عنوان محفظة usdt'),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='bank_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='عنوان محفظة usdt'),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='full_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='عنوان محفظة usdt'),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='withdrawal_method',
            field=models.CharField(choices=[('2', 'حساب بنكي')], max_length=250, verbose_name='نوع السحب'),
        ),
    ]
