# Generated by Django 4.2.14 on 2024-09-09 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0071_withdraw_iban_number_withdraw_bank_account_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='ip_info',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_facebook',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_instgram',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_linkedin',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_phone',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_snapshat',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_tiktok',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_whatsapp',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='facebook_profile',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='صفحة فيسبوك'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='instgram',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='instgram'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='land_line_number',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='هاتف ارضي'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='linkedin',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='صفحة لينكداين'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='snapshat',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='snapshat'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='tiktok',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='tiktok'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='whatsapp',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='واتساب'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='facebook',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='facebook'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='instgram',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='instgram'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='linkedin',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='linkedin'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='snapshat',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='snapshat'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='tiktok',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='tiktok'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='whatsapp',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='whatsapp'),
        ),
    ]
