# Generated by Django 4.2.14 on 2024-09-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0072_remove_userprofile_ip_info_userprofile_show_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_country_code',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
