# Generated by Django 4.2.14 on 2024-09-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0073_userprofile_phone_country_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_country_code',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='phone_country_code',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='phone_country_code',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
