# Generated by Django 4.2.14 on 2024-09-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0076_alter_subscriptionsmodel_ico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionsmodel',
            name='set_defult_price',
            field=models.BooleanField(default=False, verbose_name='عرض في السعر الافضراضي في الدول الغير مخصصة'),
        ),
    ]
