# Generated by Django 4.2.14 on 2024-09-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0077_subscriptionsmodel_set_defult_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappotp',
            name='email',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionsmodel',
            name='ico',
            field=models.ImageField(blank=True, upload_to='subscription/ico/'),
        ),
        migrations.AlterField(
            model_name='subscriptionsmodel',
            name='set_defult_price',
            field=models.BooleanField(default=False, verbose_name='عرض الباقة في الدول الغير مخصصة'),
        ),
    ]
