# Generated by Django 4.2.14 on 2024-09-17 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0079_subscriptionsmodel_show_in_distinctive_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='show_email',
            field=models.BooleanField(default=True),
        ),
    ]
