# Generated by Django 4.2.14 on 2024-09-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0080_userprofile_show_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='about_me',
            field=models.TextField(null=True, verbose_name='نبذه مختصرة عن الشركة او النشاط'),
        ),
    ]
