# Generated by Django 4.2.14 on 2024-09-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0082_subscriptionsmodel_referral_percentage_earn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionsmodel',
            name='referral_percentage_earn',
            field=models.IntegerField(default=0, verbose_name='النسبة المئوية لتسويق بلعمولة %'),
        ),
    ]
