# Generated by Django 4.2.14 on 2024-09-19 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0084_subscriptionsmodel_apply_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionsmodel',
            name='show_email',
            field=models.BooleanField(default=False, verbose_name='إظهار البريد الالكتروني'),
        ),
    ]
