# Generated by Django 4.2.14 on 2024-09-26 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0085_subscriptionsmodel_show_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='')),
                ('msg', models.TextField(verbose_name='')),
                ('send_local', models.BooleanField(default=True, verbose_name='')),
                ('send_by_email', models.BooleanField(default=True, verbose_name='')),
                ('send_by_whatsapp', models.BooleanField(default=True, verbose_name='')),
                ('msgs_count', models.IntegerField(default=0)),
                ('sended_msgs_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('1', 'يتم الارسال'), ('1', 'مكتمل')], max_length=250, verbose_name='')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.countrysmodel', verbose_name='')),
            ],
        ),
    ]
