# Generated by Django 4.2.14 on 2024-09-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0086_sendnotifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendnotifications',
            name='status',
            field=models.CharField(choices=[('1', 'يتم الارسال'), ('2', 'مكتمل')], default='1', max_length=250, verbose_name=''),
        ),
    ]
