# Generated by Django 4.2.14 on 2024-12-26 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0087_alter_sendnotifications_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='referrallinkmodel',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.subscriptionsmodel'),
        ),
        migrations.AddField(
            model_name='subscriptionsmodel',
            name='random_referral_link_chooseing_on_Subscription',
            field=models.BooleanField(default=False, verbose_name='اختيار العشوائي من روابط الأحالة عند التسجيل'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='marital_status',
            field=models.CharField(choices=[('0', 'اعزب'), ('1', 'متزوج'), ('2', 'منفصل'), ('3', 'ارمل')], max_length=255, null=True, verbose_name='الحالة الإجتماعية'),
        ),
    ]
