# Generated by Django 4.2.14 on 2024-12-27 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0088_referrallinkmodel_subscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referrallinkmodel',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.usersubscriptionmodel'),
        ),
    ]
