# Generated by Django 4.2.14 on 2024-08-15 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagesmodel',
            name='is_readed',
            field=models.BooleanField(default=False),
        ),
    ]
