# Generated by Django 4.2.14 on 2024-08-15 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_alter_messagesmodel_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagesmodel',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الانشاء'),
        ),
    ]
