# Generated by Django 4.2.14 on 2024-08-18 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messenger', '0004_alter_messagesmodel_creation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الانشاء')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_creator', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlockUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الانشاء')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_creator', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
