# Generated by Django 4.2.14 on 2024-08-21 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0005_favoriteusermodel_blockusermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagesmodel',
            name='ignore_subscription',
            field=models.BooleanField(default=False),
        ),
    ]
