# Generated by Django 4.2.14 on 2024-08-21 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0006_messagesmodel_ignore_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagesmodel',
            old_name='ignore_subscription',
            new_name='is_receiver_subscription_passed',
        ),
    ]
